/**
 * Autogenerated by Avro
 * 
 * DO NOT EDIT DIRECTLY
 */
package com.njkol.db.models;  
@SuppressWarnings("all")
@org.apache.avro.specific.AvroGenerated
public enum product_status { 
  AVAILABLE, OUT_OF_STOCK, ONLY_FEW_LEFT  ;
  public static final org.apache.avro.Schema SCHEMA$ = new org.apache.avro.Schema.Parser().parse("{\"type\":\"enum\",\"name\":\"product_status\",\"namespace\":\"com.njkol.db.models\",\"symbols\":[\"AVAILABLE\",\"OUT_OF_STOCK\",\"ONLY_FEW_LEFT\"]}");
  public static org.apache.avro.Schema getClassSchema() { return SCHEMA$; }
}
