/**
 * Autogenerated by Avro
 *
 * DO NOT EDIT DIRECTLY
 */
package com.njkol.avro.models.customer;
@org.apache.avro.specific.AvroGenerated
public enum address_type implements org.apache.avro.generic.GenericEnumSymbol<address_type> {
  POBOX, RESIDENTIAL, ENTERPRISE  ;
  public static final org.apache.avro.Schema SCHEMA$ = new org.apache.avro.Schema.Parser().parse("{\"type\":\"enum\",\"name\":\"address_type\",\"namespace\":\"com.njkol.avro.models.customer\",\"symbols\":[\"POBOX\",\"RESIDENTIAL\",\"ENTERPRISE\"]}");
  public static org.apache.avro.Schema getClassSchema() { return SCHEMA$; }
  public org.apache.avro.Schema getSchema() { return SCHEMA$; }
}
