/**
 * Autogenerated by Avro
 *
 * DO NOT EDIT DIRECTLY
 */
package com.njkol.avro.models.customer;

import org.apache.avro.generic.GenericArray;
import org.apache.avro.specific.SpecificData;
import org.apache.avro.util.Utf8;
import org.apache.avro.message.BinaryMessageEncoder;
import org.apache.avro.message.BinaryMessageDecoder;
import org.apache.avro.message.SchemaStore;

@org.apache.avro.specific.AvroGenerated
public class Customer extends org.apache.avro.specific.SpecificRecordBase implements org.apache.avro.specific.SpecificRecord {
  private static final long serialVersionUID = 6413434047305353500L;
  public static final org.apache.avro.Schema SCHEMA$ = new org.apache.avro.Schema.Parser().parse("{\"type\":\"record\",\"name\":\"Customer\",\"namespace\":\"com.njkol.avro.models.customer\",\"fields\":[{\"name\":\"first_name\",\"type\":{\"type\":\"string\",\"avro.java.string\":\"String\"}},{\"name\":\"last_name\",\"type\":{\"type\":\"string\",\"avro.java.string\":\"String\"}},{\"name\":\"age\",\"type\":\"int\"},{\"name\":\"height\",\"type\":\"float\"},{\"name\":\"weight\",\"type\":\"float\"},{\"name\":\"automated_email\",\"type\":\"boolean\",\"default\":true},{\"name\":\"customer_emails\",\"type\":{\"type\":\"array\",\"items\":{\"type\":\"string\",\"avro.java.string\":\"String\"},\"default\":[]}},{\"name\":\"customer_address\",\"type\":{\"type\":\"record\",\"name\":\"CustomerAddress\",\"fields\":[{\"name\":\"address\",\"type\":{\"type\":\"string\",\"avro.java.string\":\"String\"}},{\"name\":\"city\",\"type\":{\"type\":\"string\",\"avro.java.string\":\"String\"}},{\"name\":\"postcode\",\"type\":[{\"type\":\"string\",\"avro.java.string\":\"String\"},\"int\"]},{\"name\":\"address_type\",\"type\":{\"type\":\"enum\",\"name\":\"address_type\",\"symbols\":[\"POBOX\",\"RESIDENTIAL\",\"ENTERPRISE\"]}}]}},{\"name\":\"signup_ts\",\"type\":\"long\",\"doc\":\"EPOCH millis Timestamp at which the user signed up \",\"logicalType\":\"timestamp-millis\"}]}");
  public static org.apache.avro.Schema getClassSchema() { return SCHEMA$; }

  private static SpecificData MODEL$ = new SpecificData();

  private static final BinaryMessageEncoder<Customer> ENCODER =
      new BinaryMessageEncoder<Customer>(MODEL$, SCHEMA$);

  private static final BinaryMessageDecoder<Customer> DECODER =
      new BinaryMessageDecoder<Customer>(MODEL$, SCHEMA$);

  /**
   * Return the BinaryMessageEncoder instance used by this class.
   * @return the message encoder used by this class
   */
  public static BinaryMessageEncoder<Customer> getEncoder() {
    return ENCODER;
  }

  /**
   * Return the BinaryMessageDecoder instance used by this class.
   * @return the message decoder used by this class
   */
  public static BinaryMessageDecoder<Customer> getDecoder() {
    return DECODER;
  }

  /**
   * Create a new BinaryMessageDecoder instance for this class that uses the specified {@link SchemaStore}.
   * @param resolver a {@link SchemaStore} used to find schemas by fingerprint
   * @return a BinaryMessageDecoder instance for this class backed by the given SchemaStore
   */
  public static BinaryMessageDecoder<Customer> createDecoder(SchemaStore resolver) {
    return new BinaryMessageDecoder<Customer>(MODEL$, SCHEMA$, resolver);
  }

  /**
   * Serializes this Customer to a ByteBuffer.
   * @return a buffer holding the serialized data for this instance
   * @throws java.io.IOException if this instance could not be serialized
   */
  public java.nio.ByteBuffer toByteBuffer() throws java.io.IOException {
    return ENCODER.encode(this);
  }

  /**
   * Deserializes a Customer from a ByteBuffer.
   * @param b a byte buffer holding serialized data for an instance of this class
   * @return a Customer instance decoded from the given buffer
   * @throws java.io.IOException if the given bytes could not be deserialized into an instance of this class
   */
  public static Customer fromByteBuffer(
      java.nio.ByteBuffer b) throws java.io.IOException {
    return DECODER.decode(b);
  }

   private java.lang.String first_name;
   private java.lang.String last_name;
   private int age;
   private float height;
   private float weight;
   private boolean automated_email;
   private java.util.List<java.lang.String> customer_emails;
   private com.njkol.avro.models.customer.CustomerAddress customer_address;
  /** EPOCH millis Timestamp at which the user signed up  */
   private long signup_ts;

  /**
   * Default constructor.  Note that this does not initialize fields
   * to their default values from the schema.  If that is desired then
   * one should use <code>newBuilder()</code>.
   */
  public Customer() {}

  /**
   * All-args constructor.
   * @param first_name The new value for first_name
   * @param last_name The new value for last_name
   * @param age The new value for age
   * @param height The new value for height
   * @param weight The new value for weight
   * @param automated_email The new value for automated_email
   * @param customer_emails The new value for customer_emails
   * @param customer_address The new value for customer_address
   * @param signup_ts EPOCH millis Timestamp at which the user signed up 
   */
  public Customer(java.lang.String first_name, java.lang.String last_name, java.lang.Integer age, java.lang.Float height, java.lang.Float weight, java.lang.Boolean automated_email, java.util.List<java.lang.String> customer_emails, com.njkol.avro.models.customer.CustomerAddress customer_address, java.lang.Long signup_ts) {
    this.first_name = first_name;
    this.last_name = last_name;
    this.age = age;
    this.height = height;
    this.weight = weight;
    this.automated_email = automated_email;
    this.customer_emails = customer_emails;
    this.customer_address = customer_address;
    this.signup_ts = signup_ts;
  }

  public org.apache.avro.specific.SpecificData getSpecificData() { return MODEL$; }
  public org.apache.avro.Schema getSchema() { return SCHEMA$; }
  // Used by DatumWriter.  Applications should not call.
  public java.lang.Object get(int field$) {
    switch (field$) {
    case 0: return first_name;
    case 1: return last_name;
    case 2: return age;
    case 3: return height;
    case 4: return weight;
    case 5: return automated_email;
    case 6: return customer_emails;
    case 7: return customer_address;
    case 8: return signup_ts;
    default: throw new org.apache.avro.AvroRuntimeException("Bad index");
    }
  }

  // Used by DatumReader.  Applications should not call.
  @SuppressWarnings(value="unchecked")
  public void put(int field$, java.lang.Object value$) {
    switch (field$) {
    case 0: first_name = (java.lang.String)value$; break;
    case 1: last_name = (java.lang.String)value$; break;
    case 2: age = (java.lang.Integer)value$; break;
    case 3: height = (java.lang.Float)value$; break;
    case 4: weight = (java.lang.Float)value$; break;
    case 5: automated_email = (java.lang.Boolean)value$; break;
    case 6: customer_emails = (java.util.List<java.lang.String>)value$; break;
    case 7: customer_address = (com.njkol.avro.models.customer.CustomerAddress)value$; break;
    case 8: signup_ts = (java.lang.Long)value$; break;
    default: throw new org.apache.avro.AvroRuntimeException("Bad index");
    }
  }

  /**
   * Gets the value of the 'first_name' field.
   * @return The value of the 'first_name' field.
   */
  public java.lang.String getFirstName() {
    return first_name;
  }



  /**
   * Gets the value of the 'last_name' field.
   * @return The value of the 'last_name' field.
   */
  public java.lang.String getLastName() {
    return last_name;
  }



  /**
   * Gets the value of the 'age' field.
   * @return The value of the 'age' field.
   */
  public int getAge() {
    return age;
  }



  /**
   * Gets the value of the 'height' field.
   * @return The value of the 'height' field.
   */
  public float getHeight() {
    return height;
  }



  /**
   * Gets the value of the 'weight' field.
   * @return The value of the 'weight' field.
   */
  public float getWeight() {
    return weight;
  }



  /**
   * Gets the value of the 'automated_email' field.
   * @return The value of the 'automated_email' field.
   */
  public boolean getAutomatedEmail() {
    return automated_email;
  }



  /**
   * Gets the value of the 'customer_emails' field.
   * @return The value of the 'customer_emails' field.
   */
  public java.util.List<java.lang.String> getCustomerEmails() {
    return customer_emails;
  }



  /**
   * Gets the value of the 'customer_address' field.
   * @return The value of the 'customer_address' field.
   */
  public com.njkol.avro.models.customer.CustomerAddress getCustomerAddress() {
    return customer_address;
  }



  /**
   * Gets the value of the 'signup_ts' field.
   * @return EPOCH millis Timestamp at which the user signed up 
   */
  public long getSignupTs() {
    return signup_ts;
  }



  /**
   * Creates a new Customer RecordBuilder.
   * @return A new Customer RecordBuilder
   */
  public static com.njkol.avro.models.customer.Customer.Builder newBuilder() {
    return new com.njkol.avro.models.customer.Customer.Builder();
  }

  /**
   * Creates a new Customer RecordBuilder by copying an existing Builder.
   * @param other The existing builder to copy.
   * @return A new Customer RecordBuilder
   */
  public static com.njkol.avro.models.customer.Customer.Builder newBuilder(com.njkol.avro.models.customer.Customer.Builder other) {
    if (other == null) {
      return new com.njkol.avro.models.customer.Customer.Builder();
    } else {
      return new com.njkol.avro.models.customer.Customer.Builder(other);
    }
  }

  /**
   * Creates a new Customer RecordBuilder by copying an existing Customer instance.
   * @param other The existing instance to copy.
   * @return A new Customer RecordBuilder
   */
  public static com.njkol.avro.models.customer.Customer.Builder newBuilder(com.njkol.avro.models.customer.Customer other) {
    if (other == null) {
      return new com.njkol.avro.models.customer.Customer.Builder();
    } else {
      return new com.njkol.avro.models.customer.Customer.Builder(other);
    }
  }

  /**
   * RecordBuilder for Customer instances.
   */
  public static class Builder extends org.apache.avro.specific.SpecificRecordBuilderBase<Customer>
    implements org.apache.avro.data.RecordBuilder<Customer> {

    private java.lang.String first_name;
    private java.lang.String last_name;
    private int age;
    private float height;
    private float weight;
    private boolean automated_email;
    private java.util.List<java.lang.String> customer_emails;
    private com.njkol.avro.models.customer.CustomerAddress customer_address;
    private com.njkol.avro.models.customer.CustomerAddress.Builder customer_addressBuilder;
    /** EPOCH millis Timestamp at which the user signed up  */
    private long signup_ts;

    /** Creates a new Builder */
    private Builder() {
      super(SCHEMA$);
    }

    /**
     * Creates a Builder by copying an existing Builder.
     * @param other The existing Builder to copy.
     */
    private Builder(com.njkol.avro.models.customer.Customer.Builder other) {
      super(other);
      if (isValidValue(fields()[0], other.first_name)) {
        this.first_name = data().deepCopy(fields()[0].schema(), other.first_name);
        fieldSetFlags()[0] = other.fieldSetFlags()[0];
      }
      if (isValidValue(fields()[1], other.last_name)) {
        this.last_name = data().deepCopy(fields()[1].schema(), other.last_name);
        fieldSetFlags()[1] = other.fieldSetFlags()[1];
      }
      if (isValidValue(fields()[2], other.age)) {
        this.age = data().deepCopy(fields()[2].schema(), other.age);
        fieldSetFlags()[2] = other.fieldSetFlags()[2];
      }
      if (isValidValue(fields()[3], other.height)) {
        this.height = data().deepCopy(fields()[3].schema(), other.height);
        fieldSetFlags()[3] = other.fieldSetFlags()[3];
      }
      if (isValidValue(fields()[4], other.weight)) {
        this.weight = data().deepCopy(fields()[4].schema(), other.weight);
        fieldSetFlags()[4] = other.fieldSetFlags()[4];
      }
      if (isValidValue(fields()[5], other.automated_email)) {
        this.automated_email = data().deepCopy(fields()[5].schema(), other.automated_email);
        fieldSetFlags()[5] = other.fieldSetFlags()[5];
      }
      if (isValidValue(fields()[6], other.customer_emails)) {
        this.customer_emails = data().deepCopy(fields()[6].schema(), other.customer_emails);
        fieldSetFlags()[6] = other.fieldSetFlags()[6];
      }
      if (isValidValue(fields()[7], other.customer_address)) {
        this.customer_address = data().deepCopy(fields()[7].schema(), other.customer_address);
        fieldSetFlags()[7] = other.fieldSetFlags()[7];
      }
      if (other.hasCustomerAddressBuilder()) {
        this.customer_addressBuilder = com.njkol.avro.models.customer.CustomerAddress.newBuilder(other.getCustomerAddressBuilder());
      }
      if (isValidValue(fields()[8], other.signup_ts)) {
        this.signup_ts = data().deepCopy(fields()[8].schema(), other.signup_ts);
        fieldSetFlags()[8] = other.fieldSetFlags()[8];
      }
    }

    /**
     * Creates a Builder by copying an existing Customer instance
     * @param other The existing instance to copy.
     */
    private Builder(com.njkol.avro.models.customer.Customer other) {
      super(SCHEMA$);
      if (isValidValue(fields()[0], other.first_name)) {
        this.first_name = data().deepCopy(fields()[0].schema(), other.first_name);
        fieldSetFlags()[0] = true;
      }
      if (isValidValue(fields()[1], other.last_name)) {
        this.last_name = data().deepCopy(fields()[1].schema(), other.last_name);
        fieldSetFlags()[1] = true;
      }
      if (isValidValue(fields()[2], other.age)) {
        this.age = data().deepCopy(fields()[2].schema(), other.age);
        fieldSetFlags()[2] = true;
      }
      if (isValidValue(fields()[3], other.height)) {
        this.height = data().deepCopy(fields()[3].schema(), other.height);
        fieldSetFlags()[3] = true;
      }
      if (isValidValue(fields()[4], other.weight)) {
        this.weight = data().deepCopy(fields()[4].schema(), other.weight);
        fieldSetFlags()[4] = true;
      }
      if (isValidValue(fields()[5], other.automated_email)) {
        this.automated_email = data().deepCopy(fields()[5].schema(), other.automated_email);
        fieldSetFlags()[5] = true;
      }
      if (isValidValue(fields()[6], other.customer_emails)) {
        this.customer_emails = data().deepCopy(fields()[6].schema(), other.customer_emails);
        fieldSetFlags()[6] = true;
      }
      if (isValidValue(fields()[7], other.customer_address)) {
        this.customer_address = data().deepCopy(fields()[7].schema(), other.customer_address);
        fieldSetFlags()[7] = true;
      }
      this.customer_addressBuilder = null;
      if (isValidValue(fields()[8], other.signup_ts)) {
        this.signup_ts = data().deepCopy(fields()[8].schema(), other.signup_ts);
        fieldSetFlags()[8] = true;
      }
    }

    /**
      * Gets the value of the 'first_name' field.
      * @return The value.
      */
    public java.lang.String getFirstName() {
      return first_name;
    }


    /**
      * Sets the value of the 'first_name' field.
      * @param value The value of 'first_name'.
      * @return This builder.
      */
    public com.njkol.avro.models.customer.Customer.Builder setFirstName(java.lang.String value) {
      validate(fields()[0], value);
      this.first_name = value;
      fieldSetFlags()[0] = true;
      return this;
    }

    /**
      * Checks whether the 'first_name' field has been set.
      * @return True if the 'first_name' field has been set, false otherwise.
      */
    public boolean hasFirstName() {
      return fieldSetFlags()[0];
    }


    /**
      * Clears the value of the 'first_name' field.
      * @return This builder.
      */
    public com.njkol.avro.models.customer.Customer.Builder clearFirstName() {
      first_name = null;
      fieldSetFlags()[0] = false;
      return this;
    }

    /**
      * Gets the value of the 'last_name' field.
      * @return The value.
      */
    public java.lang.String getLastName() {
      return last_name;
    }


    /**
      * Sets the value of the 'last_name' field.
      * @param value The value of 'last_name'.
      * @return This builder.
      */
    public com.njkol.avro.models.customer.Customer.Builder setLastName(java.lang.String value) {
      validate(fields()[1], value);
      this.last_name = value;
      fieldSetFlags()[1] = true;
      return this;
    }

    /**
      * Checks whether the 'last_name' field has been set.
      * @return True if the 'last_name' field has been set, false otherwise.
      */
    public boolean hasLastName() {
      return fieldSetFlags()[1];
    }


    /**
      * Clears the value of the 'last_name' field.
      * @return This builder.
      */
    public com.njkol.avro.models.customer.Customer.Builder clearLastName() {
      last_name = null;
      fieldSetFlags()[1] = false;
      return this;
    }

    /**
      * Gets the value of the 'age' field.
      * @return The value.
      */
    public int getAge() {
      return age;
    }


    /**
      * Sets the value of the 'age' field.
      * @param value The value of 'age'.
      * @return This builder.
      */
    public com.njkol.avro.models.customer.Customer.Builder setAge(int value) {
      validate(fields()[2], value);
      this.age = value;
      fieldSetFlags()[2] = true;
      return this;
    }

    /**
      * Checks whether the 'age' field has been set.
      * @return True if the 'age' field has been set, false otherwise.
      */
    public boolean hasAge() {
      return fieldSetFlags()[2];
    }


    /**
      * Clears the value of the 'age' field.
      * @return This builder.
      */
    public com.njkol.avro.models.customer.Customer.Builder clearAge() {
      fieldSetFlags()[2] = false;
      return this;
    }

    /**
      * Gets the value of the 'height' field.
      * @return The value.
      */
    public float getHeight() {
      return height;
    }


    /**
      * Sets the value of the 'height' field.
      * @param value The value of 'height'.
      * @return This builder.
      */
    public com.njkol.avro.models.customer.Customer.Builder setHeight(float value) {
      validate(fields()[3], value);
      this.height = value;
      fieldSetFlags()[3] = true;
      return this;
    }

    /**
      * Checks whether the 'height' field has been set.
      * @return True if the 'height' field has been set, false otherwise.
      */
    public boolean hasHeight() {
      return fieldSetFlags()[3];
    }


    /**
      * Clears the value of the 'height' field.
      * @return This builder.
      */
    public com.njkol.avro.models.customer.Customer.Builder clearHeight() {
      fieldSetFlags()[3] = false;
      return this;
    }

    /**
      * Gets the value of the 'weight' field.
      * @return The value.
      */
    public float getWeight() {
      return weight;
    }


    /**
      * Sets the value of the 'weight' field.
      * @param value The value of 'weight'.
      * @return This builder.
      */
    public com.njkol.avro.models.customer.Customer.Builder setWeight(float value) {
      validate(fields()[4], value);
      this.weight = value;
      fieldSetFlags()[4] = true;
      return this;
    }

    /**
      * Checks whether the 'weight' field has been set.
      * @return True if the 'weight' field has been set, false otherwise.
      */
    public boolean hasWeight() {
      return fieldSetFlags()[4];
    }


    /**
      * Clears the value of the 'weight' field.
      * @return This builder.
      */
    public com.njkol.avro.models.customer.Customer.Builder clearWeight() {
      fieldSetFlags()[4] = false;
      return this;
    }

    /**
      * Gets the value of the 'automated_email' field.
      * @return The value.
      */
    public boolean getAutomatedEmail() {
      return automated_email;
    }


    /**
      * Sets the value of the 'automated_email' field.
      * @param value The value of 'automated_email'.
      * @return This builder.
      */
    public com.njkol.avro.models.customer.Customer.Builder setAutomatedEmail(boolean value) {
      validate(fields()[5], value);
      this.automated_email = value;
      fieldSetFlags()[5] = true;
      return this;
    }

    /**
      * Checks whether the 'automated_email' field has been set.
      * @return True if the 'automated_email' field has been set, false otherwise.
      */
    public boolean hasAutomatedEmail() {
      return fieldSetFlags()[5];
    }


    /**
      * Clears the value of the 'automated_email' field.
      * @return This builder.
      */
    public com.njkol.avro.models.customer.Customer.Builder clearAutomatedEmail() {
      fieldSetFlags()[5] = false;
      return this;
    }

    /**
      * Gets the value of the 'customer_emails' field.
      * @return The value.
      */
    public java.util.List<java.lang.String> getCustomerEmails() {
      return customer_emails;
    }


    /**
      * Sets the value of the 'customer_emails' field.
      * @param value The value of 'customer_emails'.
      * @return This builder.
      */
    public com.njkol.avro.models.customer.Customer.Builder setCustomerEmails(java.util.List<java.lang.String> value) {
      validate(fields()[6], value);
      this.customer_emails = value;
      fieldSetFlags()[6] = true;
      return this;
    }

    /**
      * Checks whether the 'customer_emails' field has been set.
      * @return True if the 'customer_emails' field has been set, false otherwise.
      */
    public boolean hasCustomerEmails() {
      return fieldSetFlags()[6];
    }


    /**
      * Clears the value of the 'customer_emails' field.
      * @return This builder.
      */
    public com.njkol.avro.models.customer.Customer.Builder clearCustomerEmails() {
      customer_emails = null;
      fieldSetFlags()[6] = false;
      return this;
    }

    /**
      * Gets the value of the 'customer_address' field.
      * @return The value.
      */
    public com.njkol.avro.models.customer.CustomerAddress getCustomerAddress() {
      return customer_address;
    }


    /**
      * Sets the value of the 'customer_address' field.
      * @param value The value of 'customer_address'.
      * @return This builder.
      */
    public com.njkol.avro.models.customer.Customer.Builder setCustomerAddress(com.njkol.avro.models.customer.CustomerAddress value) {
      validate(fields()[7], value);
      this.customer_addressBuilder = null;
      this.customer_address = value;
      fieldSetFlags()[7] = true;
      return this;
    }

    /**
      * Checks whether the 'customer_address' field has been set.
      * @return True if the 'customer_address' field has been set, false otherwise.
      */
    public boolean hasCustomerAddress() {
      return fieldSetFlags()[7];
    }

    /**
     * Gets the Builder instance for the 'customer_address' field and creates one if it doesn't exist yet.
     * @return This builder.
     */
    public com.njkol.avro.models.customer.CustomerAddress.Builder getCustomerAddressBuilder() {
      if (customer_addressBuilder == null) {
        if (hasCustomerAddress()) {
          setCustomerAddressBuilder(com.njkol.avro.models.customer.CustomerAddress.newBuilder(customer_address));
        } else {
          setCustomerAddressBuilder(com.njkol.avro.models.customer.CustomerAddress.newBuilder());
        }
      }
      return customer_addressBuilder;
    }

    /**
     * Sets the Builder instance for the 'customer_address' field
     * @param value The builder instance that must be set.
     * @return This builder.
     */
    public com.njkol.avro.models.customer.Customer.Builder setCustomerAddressBuilder(com.njkol.avro.models.customer.CustomerAddress.Builder value) {
      clearCustomerAddress();
      customer_addressBuilder = value;
      return this;
    }

    /**
     * Checks whether the 'customer_address' field has an active Builder instance
     * @return True if the 'customer_address' field has an active Builder instance
     */
    public boolean hasCustomerAddressBuilder() {
      return customer_addressBuilder != null;
    }

    /**
      * Clears the value of the 'customer_address' field.
      * @return This builder.
      */
    public com.njkol.avro.models.customer.Customer.Builder clearCustomerAddress() {
      customer_address = null;
      customer_addressBuilder = null;
      fieldSetFlags()[7] = false;
      return this;
    }

    /**
      * Gets the value of the 'signup_ts' field.
      * EPOCH millis Timestamp at which the user signed up 
      * @return The value.
      */
    public long getSignupTs() {
      return signup_ts;
    }


    /**
      * Sets the value of the 'signup_ts' field.
      * EPOCH millis Timestamp at which the user signed up 
      * @param value The value of 'signup_ts'.
      * @return This builder.
      */
    public com.njkol.avro.models.customer.Customer.Builder setSignupTs(long value) {
      validate(fields()[8], value);
      this.signup_ts = value;
      fieldSetFlags()[8] = true;
      return this;
    }

    /**
      * Checks whether the 'signup_ts' field has been set.
      * EPOCH millis Timestamp at which the user signed up 
      * @return True if the 'signup_ts' field has been set, false otherwise.
      */
    public boolean hasSignupTs() {
      return fieldSetFlags()[8];
    }


    /**
      * Clears the value of the 'signup_ts' field.
      * EPOCH millis Timestamp at which the user signed up 
      * @return This builder.
      */
    public com.njkol.avro.models.customer.Customer.Builder clearSignupTs() {
      fieldSetFlags()[8] = false;
      return this;
    }

    @SuppressWarnings("unchecked")
    public Customer build() {
      try {
        Customer record = new Customer();
        record.first_name = fieldSetFlags()[0] ? this.first_name : (java.lang.String) defaultValue(fields()[0]);
        record.last_name = fieldSetFlags()[1] ? this.last_name : (java.lang.String) defaultValue(fields()[1]);
        record.age = fieldSetFlags()[2] ? this.age : (java.lang.Integer) defaultValue(fields()[2]);
        record.height = fieldSetFlags()[3] ? this.height : (java.lang.Float) defaultValue(fields()[3]);
        record.weight = fieldSetFlags()[4] ? this.weight : (java.lang.Float) defaultValue(fields()[4]);
        record.automated_email = fieldSetFlags()[5] ? this.automated_email : (java.lang.Boolean) defaultValue(fields()[5]);
        record.customer_emails = fieldSetFlags()[6] ? this.customer_emails : (java.util.List<java.lang.String>) defaultValue(fields()[6]);
        if (customer_addressBuilder != null) {
          try {
            record.customer_address = this.customer_addressBuilder.build();
          } catch (org.apache.avro.AvroMissingFieldException e) {
            e.addParentField(record.getSchema().getField("customer_address"));
            throw e;
          }
        } else {
          record.customer_address = fieldSetFlags()[7] ? this.customer_address : (com.njkol.avro.models.customer.CustomerAddress) defaultValue(fields()[7]);
        }
        record.signup_ts = fieldSetFlags()[8] ? this.signup_ts : (java.lang.Long) defaultValue(fields()[8]);
        return record;
      } catch (org.apache.avro.AvroMissingFieldException e) {
        throw e;
      } catch (java.lang.Exception e) {
        throw new org.apache.avro.AvroRuntimeException(e);
      }
    }
  }

  @SuppressWarnings("unchecked")
  private static final org.apache.avro.io.DatumWriter<Customer>
    WRITER$ = (org.apache.avro.io.DatumWriter<Customer>)MODEL$.createDatumWriter(SCHEMA$);

  @Override public void writeExternal(java.io.ObjectOutput out)
    throws java.io.IOException {
    WRITER$.write(this, SpecificData.getEncoder(out));
  }

  @SuppressWarnings("unchecked")
  private static final org.apache.avro.io.DatumReader<Customer>
    READER$ = (org.apache.avro.io.DatumReader<Customer>)MODEL$.createDatumReader(SCHEMA$);

  @Override public void readExternal(java.io.ObjectInput in)
    throws java.io.IOException {
    READER$.read(this, SpecificData.getDecoder(in));
  }

}










